language: node_js
cache:
  directories:
    - ~/.npm
    - node_modules
addons:
  chrome: stable
node_js:
  - stable
  - '10'
before_install:
  - sh ./build/setup_puppeteer.sh
install:
  - yarn
script:
  - npm run test
  - npm run coverage
  - npm run build
